IF DB_ID('OnlineStore') IS NULL
BEGIN
    CREATE DATABASE OnlineStore;
END

IF OBJECT_ID(N'[dbo].[__MigrationHistory]', 'U') IS NULL
BEGIN
    CREATE TABLE __MigrationHistory (
        MigrationID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        MigrationName NVARCHAR(255) NOT NULL,
        MigrationHash NVARCHAR(64) NOT NULL,
        AppliedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
    );
END

-- ================= Customer =================
IF OBJECT_ID('Customer', 'U') IS NULL
CREATE TABLE Customer (
    CustomerID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) NOT NULL UNIQUE,
    Phone NVARCHAR(20) NOT NULL,
    Address_Street NVARCHAR(4000) NOT NULL DEFAULT '',
Address_City NVARCHAR(4000) NOT NULL DEFAULT '',
Address_ZipCode NVARCHAR(4000) NOT NULL DEFAULT '',
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

-- ================= Category =================
IF OBJECT_ID('Category', 'U') IS NULL
CREATE TABLE Category (
    CategoryID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Name NVARCHAR(50) NOT NULL,
    Description NVARCHAR(500) NULL
);

--  Product 
IF OBJECT_ID('Product', 'U') IS NULL
CREATE TABLE Product (
    ProductID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Description NVARCHAR(500) NULL,
    Price DECIMAL(10,2) NOT NULL CHECK (Price > 0),
    Stock INT NOT NULL CHECK (Stock >= 0),
    CategoryID INT NOT NULL,
    Status NVARCHAR(50) NOT NULL DEFAULT 'Active',
    IsDeleted BIT NOT NULL DEFAULT 0,
    Metadata NVARCHAR(MAX) NULL, 
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    FOREIGN KEY (CategoryID) REFERENCES Category(CategoryID) ON UPDATE CASCADE ON DELETE NO ACTION
);


-- Orders 
IF OBJECT_ID('Orders', 'U') IS NULL
CREATE TABLE Orders (
    OrderID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    CustomerID INT NOT NULL,
    OrderDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    Status NVARCHAR(50) NOT NULL DEFAULT 'Pending',
    TotalAmount DECIMAL(10,2) NOT NULL DEFAULT 0,
    FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID) ON UPDATE CASCADE ON DELETE NO ACTION
);

-- OrderItem
IF OBJECT_ID('OrderItem', 'U') IS NULL
CREATE TABLE OrderItem (
    OrderItemID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    OrderID INT NOT NULL,
    ProductID INT NOT NULL,
    Amount INT NOT NULL CHECK (Amount > 0),
    Price DECIMAL(10,2) NOT NULL CHECK (Price > 0),
    FOREIGN KEY (OrderID) REFERENCES Orders(OrderID) ON DELETE CASCADE,
    FOREIGN KEY (ProductID) REFERENCES Product(ProductID) ON DELETE NO ACTION
);

--  Payment
IF OBJECT_ID('Payment', 'U') IS NULL
CREATE TABLE Payment (
    PaymentID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    OrderID INT NOT NULL,
    Amount DECIMAL(10,2) NOT NULL CHECK (Amount > 0),
    PaymentDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    Method NVARCHAR(50) NOT NULL,
    FOREIGN KEY (OrderID) REFERENCES Orders(OrderID) ON DELETE CASCADE
);

--  Delivery 
IF OBJECT_ID('Delivery', 'U') IS NULL
CREATE TABLE Delivery (
    DeliveryID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    OrderID INT NOT NULL,
    Type NVARCHAR(50) NOT NULL,
    Cost DECIMAL(10,2) NOT NULL CHECK (Cost >= 0),
    Status NVARCHAR(50) NULL DEFAULT 'Processing',
    DeliveryDate DATETIME2 NULL,
    FOREIGN KEY (OrderID) REFERENCES Orders(OrderID) ON DELETE CASCADE
);
